create database Projeto;

Use Projeto;

DESC CLIENTE

create table CLIENTE(
	NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT (11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/*3 FORMAS DE INSERIR DADOS NA TABELA*/

/*1-) OMITINDO AS COLUNAS*/

/* QUANDO OMITIMOS É NECESSARIO COLOCAR TODAS AS COLUNAS DA TABELA*/

INSERT INTO CLIENTE VALUES('JOÃO','M','JOAO@GMAIL.COM',988630273,'22923119','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/*2-) COLOCANDO AS COLUNAS*/

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/*3-) INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES	('ANA','F','ANA@GLOBO.COM',85548962,'548556968',' PRES ANTONIO CARLOS - CENTRO - SÃO PAULO-SP'),
							('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

DESC CLIENTE


INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);

SELECT * FROM CLIENTE

/*COMANDO SELECT*/

SHOW TABLES;

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;/*VER DATA E HORA*/

select 'FELIPE MAFRA';/*VER REGISTRO ESPECIFICO*/

select 'BANCO DE DADOS';/*MOSTRAR BANCO DE DADOS*/

/*ALIAS DE COLUNAS*/

SELECT NOME,SEXO,EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE,SEXO,EMAIL FROM CLIENTE;/*ALTERA O NOME DA COLUNA PARA CLIENTE*/ 

SELECT NOME,SEXO,EMAIL,ENDERECO FROM CLIENTE;

SELECT EMAIL,SEXO,ENDERECO,NOME FROM CLIENTE;/*ALTERAR A ORDEM DE EXIBIÇÃO*/

SELECT EMAIL,SEXO,ENDERECO,NOME, NOW() AS DATA_HORA FROM CLIENTE;/*ALTERAR A ORDEM DE EXIBIÇÃO*/

/*APENAS PARA FINS ACADEMICOS*/

SELECT * FROM CLIENTE;

/*FILTRANDO DADOS COM WHERE E LIKE*/

SELECT NOME, SEXO FROM CLIENTE;

/*FILTRO FUNCIONA EM NIVEL DE LINHA E NÃO DE COLUNAS*/
/*FILTRANDO*/

SELECT NOME,SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME,SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ'; /*TEM QUE SER EXATAMENTE IGUAL O CAMPO';

/*ULTILIZANDO LIKE*/

SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/*LIKE TRABALHA COM CARACTER CORINGA % -> QUALQUER COISA*/

SELECT NOME,SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME,SEXO,ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME,SEXO,ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME,SEXO,ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';


/*Tabela verdade*/

/*OR - OU*/
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO ='M'
OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO ='F'
OR ENDERECO LIKE '%ESTACIO';

/*AND - E*/

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO ='M'
AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO ='F'
AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS*/

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TABELA CLIENTE"
FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LÓGICOS*/

/* 1 MILHÃO DE REGISTROS

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDIÇÃO
SEXO = flushCIDADE = RIO DE JANEIRO

SITUAÇÃO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUAÇÃO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE CIDADE =  'RIO DE JANEIRO'
AND SEXO ='F';
*/
 nota fiscal 347190
